# Generated by Django 3.1.3 on 2021-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20201215_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(max_length=4),
        ),
    ]
