# Generated by Django 3.1.3 on 2021-01-09 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0006_auto_20210108_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cozinheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cozinheiro', models.CharField(max_length=200)),
                ('especialidades', models.TextField()),
                ('experiencias', models.TextField()),
                ('estado', models.CharField(max_length=4)),
                ('idade', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('data_cozinheiro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_cozinheiro', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('publicada', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
